/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.outsiderninjadevs.menubuilderconsole;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Menu classUnderTest = new Menu(null, null);
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.test());
    }
}
