/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.outsiderninjadevs.menubuilderconsole;

import org.junit.Test;

public class LibraryTest {
    @Test
    public void mainClassshouldExist() throws ClassNotFoundException {
        System.out.println(Class.forName("com.outsiderninjadevs.menubuilderconsole.Menu"));
    }
}
